dist: xenial

language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install .
  - pip install pytest pytest-cov coveralls pyyaml

script:
  - pytest --cov=watchdog watchdog/tests
after_success:
  - coveralls
